baseURL = "https://leivinkivi.fi/"

languageCode = "fi-fi"

title = "Leivinkivi"

enableGitInfo = true

[params]
    BookRepo = "https://github.com/leivinkivi/leivinkivi.github.io"
    BookComments = false
